name: Monorepo CD

on:
  release:
    types:
      - published

env:
  NODE_VERSION: 24

jobs:
  get-version:
    name: Get Version

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.version-without-v }}

    steps:
      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Log Version
        run: echo "${{ steps.get_version.outputs.version-without-v }}"

  ci:
    needs:
      - get-version
    name: Run Monorepo CI
    uses: ./.github/workflows/src-ci.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
    secrets: inherit

  deploy:
    needs:
      - get-version
      - ci

    name: Deploy

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Download Build
        uses: actions/download-artifact@v8
        with:
          name: Build
          path: packages

      - name: Get Latest Tag
        uses: tobysmith568/npm-publish-latest-tag@v1
        id: latest_tag
        with:
          package-json: packages/generate-license-file/dist/package.json

      - name: Publish generate-license-file
        run: bun run tools/scripts/publish.mjs generate-license-file ${{ steps.latest_tag.outputs.latest-tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - name: Publish webpack-plugin
        run: bun run tools/scripts/publish.mjs webpack-plugin ${{ steps.latest_tag.outputs.latest-tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
