name: Website CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Run Website CI
    uses: ./.github/workflows/website-ci.yml
    secrets: inherit

  deploy:
    needs:
      - ci

    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Download Website Build
        uses: actions/download-artifact@v4
        with:
          name: Website

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
